-- 120 秒保留期改成**墙钟**：把"服务器什么时候接手这一座"的绝对时刻存进库里。
--
-- 为什么要存：原先 `reconnectDeadline` 只在内存里，触发它的定时器也只在内存里。
-- 于是服务一重启就出现两种都不对的可能：
--   * 按"重新计时"处理 —— 等于白送一个新的 120 秒，停机多久都还能再拿一次；
--   * 干脆不管 —— 这一座永远停在"等人工操作"，把整局卡死。
--
-- 存成绝对时刻之后，任何进程、任何时刻读到的都是同一个答案：
--
--   reconnect_deadline IS NULL        ⇒ 没有保护期（在线 / 已托管 / 已结算）
--   now <= reconnect_deadline         ⇒ 仍在人工控制权保护期内
--   now >  reconnect_deadline         ⇒ 保护期已过 ⇒ HUMAN 转 TRUSTEE
--
-- ⚠️ 内存里的定时器**仍然保留**，但它只是"到点了提醒我看一眼"的调度手段，
--    不是真相来源。真相是这一列。定时器到点后照样要走一遍同样的判断
--    （见 `MatchRoom.expireOverdueControl`），所以两者不会打架，也不会重复动作。
--
-- 可空：绝大多数行都不该有这个时间 —— 在线的、已托管的、已结束的、在等待期的，
-- 全都是 NULL。只有"异常断线且还有人工控制权"的座位才带一个时刻。
ALTER TABLE match_room_players
  ADD COLUMN reconnect_deadline TIMESTAMPTZ;
