const style = document.createElement("style");
style.textContent = `
body:has(.lobby),body:has(.chat-shell){background:#ededed;color:#24292c;color-scheme:light}
body:has(.lobby) #bar,body:has(.chat-shell) #bar{background:#f7f7f7;color:#333;border-bottom:1px solid #dedede}
body:has(.lobby) #app,body:has(.chat-shell) #app{max-width:1060px;margin:auto;padding:20px}
.lobby,.chat-shell{font-family:"Microsoft YaHei",sans-serif;background:#fff;border:1px solid #dedede;border-radius:14px;overflow:hidden;color:#202624}
.lobby button,.chat-shell button,.social-dialog button{background:#f0f2f1;color:#26342d;border:1px solid #d9dfdb;padding:10px 14px;border-radius:7px;cursor:pointer}
.lobby button.primary,.chat-shell button.primary,.social-dialog button.primary{background:#07a653;color:white;border:0}
.lobby .text,.chat-shell .text,.social-dialog .text{min-width:0;background:white;color:#222;border:1px solid #d6ddd8;border-radius:6px;padding:12px;font:inherit}
.lobby .hint,.chat-shell .hint,.social-dialog .hint{color:#7d8580}
.social-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:24px}
.social-heading h1,.social-heading h2{margin:0}.social-heading p{margin:8px 0 0}
.lobby .group-search{display:block;width:calc(100% - 48px);text-align:left;color:#8c948e;margin:0 24px 18px;background:#f2f3f2;border:0}
.lobby-room-actions{display:flex;gap:10px;flex-wrap:wrap;padding:0 24px 22px;border-bottom:1px solid #eee}.lobby-room-actions input{width:140px}
.list-heading{font-size:14px;color:#929a94;padding:16px 24px 8px;margin:0}
.conversation-list{min-height:300px}.lobby .conversation{width:100%;display:flex;align-items:center;gap:16px;text-align:left;border:0;border-bottom:1px solid #f0f0f0;border-radius:0;background:white;padding:18px 24px}
.lobby .conversation:hover{background:#f4f8f5}.conversation-copy{flex:1;min-width:0}.conversation-copy strong{font-size:17px}.conversation-copy p{margin:8px 0 0;color:#8a948d;font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.social-avatar{position:relative;display:inline-flex;align-items:center;justify-content:center;background:#dce9e1;color:#366848;width:48px;height:48px;flex:0 0 48px;border-radius:9px;overflow:hidden;font-size:22px;font-weight:bold}
.social-avatar img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
.social-footer{padding:16px 24px;display:flex;justify-content:space-between;align-items:center;border-top:1px solid #eee;font-size:13px;color:#858e88}
.social-empty{padding:50px 20px;text-align:center;color:#8f9691}.social-dialog{max-width:650px;width:calc(100% - 40px);max-height:85vh;border:0;border-radius:12px;padding:0;background:white;color:#222;box-shadow:0 15px 70px #0004}.social-dialog::backdrop{background:#0006}.dialog-body{padding:0 24px 24px;display:flex;gap:12px;flex-direction:column}.group-result,.member-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:14px 0;border-bottom:1px solid #eee}.member-row button{font-size:12px}.member-row p{margin:6px 0}
.chat-shell{height:calc(100dvh - 115px);min-height:430px;display:flex;flex-direction:column}.chat-header{background:#fafafa;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 20px;border-bottom:1px solid #ddd}.chat-header>div{flex:1;text-align:center}.chat-header p{margin:6px 0 0;font-size:12px}.chat-messages{background:#ededed;flex:1;min-height:0;overflow:auto;padding:24px;overflow-anchor:auto}.chat-message{display:flex;gap:12px;margin:0 0 24px;align-items:flex-start}.chat-message.mine{flex-direction:row-reverse}.chat-message-content{max-width:75%;display:flex;flex-direction:column;gap:7px;align-items:flex-start}.mine .chat-message-content{align-items:flex-end}.chat-message-content>small{color:#8a928c;font-size:12px}.chat-bubble{background:white;padding:12px 15px;border-radius:7px;white-space:pre-wrap;overflow-wrap:anywhere;color:#222;line-height:1.6}.mine .chat-bubble{background:#a5e877}.chat-image{max-width:240px;max-height:260px;display:block;border-radius:4px;cursor:zoom-in}.chat-bubble audio{max-width:220px}.chat-composer{display:flex;align-items:center;gap:10px;padding:15px;background:#fafafa;border-top:1px solid #ddd}.chat-composer input.text{flex:1;min-width:0;width:0}.chat-status{margin:0;background:#fff6df;color:#8e632c;font-size:13px;text-align:center}.chat-status:empty{display:none}.chat-shell .recall-message{font-size:11px;border:0;background:none;color:#849186;padding:0}.system-message{text-align:center;color:#9a9f9b;font-size:12px}
.chat-shell .room-invite-card{display:block;text-align:left;background:white;min-width:210px;border:0;padding:6px;color:#263b2c}.room-invite-card strong{display:block}.room-invite-card small{display:block;border-top:1px solid #eee;padding-top:10px;color:#899087}.invite-icon{display:block;font-size:30px;color:#07a653}.room-invite-card p{margin:8px 0 14px}
.waiting-table{position:relative;min-height:620px;max-width:1050px;width:100%;margin:16px auto;border:12px solid #644c35;border-radius:90px;background:radial-gradient(ellipse,#347754,#154c35);box-shadow:inset 0 0 70px #0004;color:white}.waiting-seat{position:absolute;display:flex;flex-direction:column;align-items:center;gap:6px;width:150px;text-align:center}.waiting-seat.north{top:24px;left:calc(50% - 75px)}.waiting-seat.south{bottom:24px;left:calc(50% - 75px)}.waiting-seat.west{left:20px;top:calc(50% - 65px)}.waiting-seat.east{right:20px;top:calc(50% - 65px)}.waiting-seat small{font-size:11px;color:#c3dbc9}.waiting-center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);text-align:center;width:250px}.owner-badge{background:#dfbc6f;color:#48371b;border-radius:4px;padding:3px 10px;font-size:12px}
@media(max-width:600px){body:has(.lobby) #app,body:has(.chat-shell) #app{padding:0}.lobby,.chat-shell{border-radius:0;border:0}.chat-shell{height:calc(100dvh - 65px)}.social-heading{padding:18px}.lobby-room-actions{padding:0 18px 18px}.social-footer{gap:8px;flex-wrap:wrap}.chat-messages{padding:15px 10px}.chat-message-content{max-width:76%}.chat-composer{padding:10px 8px;gap:6px}.chat-composer button{padding:10px}.chat-image{max-width:175px}.chat-header{padding:12px 8px;gap:8px}.waiting-table{min-height:560px;border-width:6px;border-radius:40px}.waiting-seat{width:104px}.waiting-seat.north,.waiting-seat.south{left:calc(50% - 52px)}.waiting-seat.west{left:4px}.waiting-seat.east{right:4px}.waiting-center{width:140px}.waiting-center h2{font-size:16px}.waiting-center p{font-size:12px}.waiting-seat strong{font-size:13px}.waiting-seat small{font-size:10px}}
`;
document.head.append(style);
export {};
